export const FETCH_BLOGS = "FETCH_BLOGS"
export const FETCH_COMMENTS = "FETCH_COMMENTS"

export const SET_CURRENT_POST = "SET_CURRENT_POST"
export const CLEAR_CURRENT_POST = "CLEAR_CURRENT_POST"

export const SET_LOADING_TRUE = "SET_LOADING_TRUE"
export const SET_LOADING_FALSE = "SET_LOADING_FALSE"

export const SET_ERROR = "SET_ERROR"
export const CLEAR_ERROR = "CLEAR_ERROR"


export const SET_SEARCH_TEXT = "SET_SEARCH_TEXT"
export const CLEAR_SEARCH_TEXT = "CLEAR_SEARCH_TEXT"
